name: 'Conventional Labeler'
description: 'A Pull request labeler using conventional commit standard'
branding:
  icon: align-center
  color: green

inputs:
  key:
    description: 'Azure OpenAI Key'
    required: true
  endpoint:
    description: 'Azure OpenAI Endpoint'
    required: true
  ignoreFiles:
    description: 'Files to ignore'
    required: false
  promptFile:
    description: 'Prompt file'
    required: false
  targetBranch:
    description: 'Target branch'
    required: false
    default: 'main'
  prDescription:
    description: 'Pull request description'
    required: false
  prTitle:
    description: 'Pull request title'
    required: false
outputs:
  comments:
    description: Generated labels for your pull request.
runs:
  using: 'node20'
  main: 'dist/index.js'